import sqlite3
print('\n')
print('Library imported for databases')
print('\n')

def main():
    print('Connecting to the database.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    db = sqlite3.connect('my_first_python_database.db')
    cur = db.cursor()
    print('Database Created.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    cur.execute("DROP TABLE IF EXISTS test")
    cur.execute("""
        CREATE TABLE test(
            id INTEGER, string TEXT, number INTEGER
            )    
    """)
    print('Table Created')
    print('\n')
    print('Inserting rows')
    print('\n')
    cur.execute("""
        INSERT INTO test (id, string, number) VALUES (1, "asd",2)
    """) ##### for every row that you want enter, you need to do cur.execute
    print('\n')
    print('Row insterted')
    print('\n')
    print('Committing')
    print('\n')
    db.commit()
    db.close()

main()